spring:
  jpa:
    open-in-view: false
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'false'
  datasource:
    password: '1234'
    url: 'jdbc:mariadb://localhost:3306/study_db'
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'studyMaster'
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: 'true'
    call-setters-on-nulls: true

